#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project62PM1.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NewsMngDB")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_TinTuc_DanhMuc(tbl_TinTuc_DanhMuc instance);
    partial void Updatetbl_TinTuc_DanhMuc(tbl_TinTuc_DanhMuc instance);
    partial void Deletetbl_TinTuc_DanhMuc(tbl_TinTuc_DanhMuc instance);
    partial void Inserttbl_DanhMuc(tbl_DanhMuc instance);
    partial void Updatetbl_DanhMuc(tbl_DanhMuc instance);
    partial void Deletetbl_DanhMuc(tbl_DanhMuc instance);
    partial void Inserttbl_cmd(tbl_cmd instance);
    partial void Updatetbl_cmd(tbl_cmd instance);
    partial void Deletetbl_cmd(tbl_cmd instance);
    partial void Inserttbl_khoahoc(tbl_khoahoc instance);
    partial void Updatetbl_khoahoc(tbl_khoahoc instance);
    partial void Deletetbl_khoahoc(tbl_khoahoc instance);
    partial void Inserttbl_User(tbl_User instance);
    partial void Updatetbl_User(tbl_User instance);
    partial void Deletetbl_User(tbl_User instance);
    partial void Inserttbl_chart(tbl_chart instance);
    partial void Updatetbl_chart(tbl_chart instance);
    partial void Deletetbl_chart(tbl_chart instance);
    partial void Inserttbl_nhatki(tbl_nhatki instance);
    partial void Updatetbl_nhatki(tbl_nhatki instance);
    partial void Deletetbl_nhatki(tbl_nhatki instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NewsMngDBConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_TinTuc_DanhMuc> tbl_TinTuc_DanhMucs
		{
			get
			{
				return this.GetTable<tbl_TinTuc_DanhMuc>();
			}
		}
		
		public System.Data.Linq.Table<tbl_TinTuc> tbl_TinTucs
		{
			get
			{
				return this.GetTable<tbl_TinTuc>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DanhMuc> tbl_DanhMucs
		{
			get
			{
				return this.GetTable<tbl_DanhMuc>();
			}
		}
		
		public System.Data.Linq.Table<tbl_cmd> tbl_cmds
		{
			get
			{
				return this.GetTable<tbl_cmd>();
			}
		}
		
		public System.Data.Linq.Table<tbl_khoahoc> tbl_khoahocs
		{
			get
			{
				return this.GetTable<tbl_khoahoc>();
			}
		}
		
		public System.Data.Linq.Table<tbl_User> tbl_Users
		{
			get
			{
				return this.GetTable<tbl_User>();
			}
		}
		
		public System.Data.Linq.Table<tbl_chart> tbl_charts
		{
			get
			{
				return this.GetTable<tbl_chart>();
			}
		}
		
		public System.Data.Linq.Table<tbl_nhatki> tbl_nhatkis
		{
			get
			{
				return this.GetTable<tbl_nhatki>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_TinTuc_DanhMuc")]
	public partial class tbl_TinTuc_DanhMuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Nullable<long> _DanhMucId;
		
		private System.Nullable<System.Guid> _TinTucId;
		
		private System.Nullable<System.DateTime> _Create_at;
		
		private System.Nullable<System.DateTime> _LastEdit_at;
		
		private System.Nullable<System.DateTime> _Delete_at;
		
		private System.Nullable<byte> _isDelete;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnDanhMucIdChanging(System.Nullable<long> value);
    partial void OnDanhMucIdChanged();
    partial void OnTinTucIdChanging(System.Nullable<System.Guid> value);
    partial void OnTinTucIdChanged();
    partial void OnCreate_atChanging(System.Nullable<System.DateTime> value);
    partial void OnCreate_atChanged();
    partial void OnLastEdit_atChanging(System.Nullable<System.DateTime> value);
    partial void OnLastEdit_atChanged();
    partial void OnDelete_atChanging(System.Nullable<System.DateTime> value);
    partial void OnDelete_atChanged();
    partial void OnisDeleteChanging(System.Nullable<byte> value);
    partial void OnisDeleteChanged();
    #endregion
		
		public tbl_TinTuc_DanhMuc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhMucId", DbType="BigInt")]
		public System.Nullable<long> DanhMucId
		{
			get
			{
				return this._DanhMucId;
			}
			set
			{
				if ((this._DanhMucId != value))
				{
					this.OnDanhMucIdChanging(value);
					this.SendPropertyChanging();
					this._DanhMucId = value;
					this.SendPropertyChanged("DanhMucId");
					this.OnDanhMucIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinTucId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> TinTucId
		{
			get
			{
				return this._TinTucId;
			}
			set
			{
				if ((this._TinTucId != value))
				{
					this.OnTinTucIdChanging(value);
					this.SendPropertyChanging();
					this._TinTucId = value;
					this.SendPropertyChanged("TinTucId");
					this.OnTinTucIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> Create_at
		{
			get
			{
				return this._Create_at;
			}
			set
			{
				if ((this._Create_at != value))
				{
					this.OnCreate_atChanging(value);
					this.SendPropertyChanging();
					this._Create_at = value;
					this.SendPropertyChanged("Create_at");
					this.OnCreate_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastEdit_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastEdit_at
		{
			get
			{
				return this._LastEdit_at;
			}
			set
			{
				if ((this._LastEdit_at != value))
				{
					this.OnLastEdit_atChanging(value);
					this.SendPropertyChanging();
					this._LastEdit_at = value;
					this.SendPropertyChanged("LastEdit_at");
					this.OnLastEdit_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delete_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> Delete_at
		{
			get
			{
				return this._Delete_at;
			}
			set
			{
				if ((this._Delete_at != value))
				{
					this.OnDelete_atChanging(value);
					this.SendPropertyChanging();
					this._Delete_at = value;
					this.SendPropertyChanged("Delete_at");
					this.OnDelete_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDelete", DbType="TinyInt")]
		public System.Nullable<byte> isDelete
		{
			get
			{
				return this._isDelete;
			}
			set
			{
				if ((this._isDelete != value))
				{
					this.OnisDeleteChanging(value);
					this.SendPropertyChanging();
					this._isDelete = value;
					this.SendPropertyChanged("isDelete");
					this.OnisDeleteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_TinTuc")]
	public partial class tbl_TinTuc
	{
		
		private string _Id;
		
		private string _TieuDe;
		
		private string _MoTa;
		
		private string _NoiDung;
		
		private System.Nullable<System.DateTime> _ThoiGianHienThi;
		
		private string _target;
		
		private System.Nullable<byte> _isSendMail;
		
		private System.Nullable<System.DateTime> _Create_at;
		
		private System.Nullable<System.DateTime> _LastEdit_at;
		
		private System.Nullable<System.DateTime> _Delete_at;
		
		private System.Nullable<byte> _isDelete;
		
		public tbl_TinTuc()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(500)")]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this._TieuDe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this._MoTa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this._NoiDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianHienThi", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianHienThi
		{
			get
			{
				return this._ThoiGianHienThi;
			}
			set
			{
				if ((this._ThoiGianHienThi != value))
				{
					this._ThoiGianHienThi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_target", DbType="NVarChar(20)")]
		public string target
		{
			get
			{
				return this._target;
			}
			set
			{
				if ((this._target != value))
				{
					this._target = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isSendMail", DbType="TinyInt")]
		public System.Nullable<byte> isSendMail
		{
			get
			{
				return this._isSendMail;
			}
			set
			{
				if ((this._isSendMail != value))
				{
					this._isSendMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> Create_at
		{
			get
			{
				return this._Create_at;
			}
			set
			{
				if ((this._Create_at != value))
				{
					this._Create_at = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastEdit_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastEdit_at
		{
			get
			{
				return this._LastEdit_at;
			}
			set
			{
				if ((this._LastEdit_at != value))
				{
					this._LastEdit_at = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delete_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> Delete_at
		{
			get
			{
				return this._Delete_at;
			}
			set
			{
				if ((this._Delete_at != value))
				{
					this._Delete_at = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDelete", DbType="TinyInt")]
		public System.Nullable<byte> isDelete
		{
			get
			{
				return this._isDelete;
			}
			set
			{
				if ((this._isDelete != value))
				{
					this._isDelete = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DanhMuc")]
	public partial class tbl_DanhMuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _TieuDe;
		
		private string _URL;
		
		private System.Nullable<long> _Id_Cha;
		
		private string _MoTa;
		
		private string _GioiThieu;
		
		private System.Nullable<int> _MainMenu_Order;
		
		private System.Nullable<byte> _is_ShowMainMenu;
		
		private System.Nullable<int> _HeadMenu_Order;
		
		private System.Nullable<byte> _is_ShowHeadeMenu;
		
		private System.Nullable<System.DateTime> _Create_at;
		
		private System.Nullable<System.DateTime> _LastEdit_at;
		
		private System.Nullable<System.DateTime> _Delete_at;
		
		private System.Nullable<byte> _isDelete;
		
		private string _ExtentData;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnId_ChaChanging(System.Nullable<long> value);
    partial void OnId_ChaChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnGioiThieuChanging(string value);
    partial void OnGioiThieuChanged();
    partial void OnMainMenu_OrderChanging(System.Nullable<int> value);
    partial void OnMainMenu_OrderChanged();
    partial void Onis_ShowMainMenuChanging(System.Nullable<byte> value);
    partial void Onis_ShowMainMenuChanged();
    partial void OnHeadMenu_OrderChanging(System.Nullable<int> value);
    partial void OnHeadMenu_OrderChanged();
    partial void Onis_ShowHeadeMenuChanging(System.Nullable<byte> value);
    partial void Onis_ShowHeadeMenuChanged();
    partial void OnCreate_atChanging(System.Nullable<System.DateTime> value);
    partial void OnCreate_atChanged();
    partial void OnLastEdit_atChanging(System.Nullable<System.DateTime> value);
    partial void OnLastEdit_atChanged();
    partial void OnDelete_atChanging(System.Nullable<System.DateTime> value);
    partial void OnDelete_atChanged();
    partial void OnisDeleteChanging(System.Nullable<byte> value);
    partial void OnisDeleteChanged();
    partial void OnExtentDataChanging(string value);
    partial void OnExtentDataChanged();
    #endregion
		
		public tbl_DanhMuc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(1000)")]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Cha", DbType="BigInt")]
		public System.Nullable<long> Id_Cha
		{
			get
			{
				return this._Id_Cha;
			}
			set
			{
				if ((this._Id_Cha != value))
				{
					this.OnId_ChaChanging(value);
					this.SendPropertyChanging();
					this._Id_Cha = value;
					this.SendPropertyChanged("Id_Cha");
					this.OnId_ChaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiThieu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string GioiThieu
		{
			get
			{
				return this._GioiThieu;
			}
			set
			{
				if ((this._GioiThieu != value))
				{
					this.OnGioiThieuChanging(value);
					this.SendPropertyChanging();
					this._GioiThieu = value;
					this.SendPropertyChanged("GioiThieu");
					this.OnGioiThieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainMenu_Order", DbType="Int")]
		public System.Nullable<int> MainMenu_Order
		{
			get
			{
				return this._MainMenu_Order;
			}
			set
			{
				if ((this._MainMenu_Order != value))
				{
					this.OnMainMenu_OrderChanging(value);
					this.SendPropertyChanging();
					this._MainMenu_Order = value;
					this.SendPropertyChanged("MainMenu_Order");
					this.OnMainMenu_OrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ShowMainMenu", DbType="TinyInt")]
		public System.Nullable<byte> is_ShowMainMenu
		{
			get
			{
				return this._is_ShowMainMenu;
			}
			set
			{
				if ((this._is_ShowMainMenu != value))
				{
					this.Onis_ShowMainMenuChanging(value);
					this.SendPropertyChanging();
					this._is_ShowMainMenu = value;
					this.SendPropertyChanged("is_ShowMainMenu");
					this.Onis_ShowMainMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeadMenu_Order", DbType="Int")]
		public System.Nullable<int> HeadMenu_Order
		{
			get
			{
				return this._HeadMenu_Order;
			}
			set
			{
				if ((this._HeadMenu_Order != value))
				{
					this.OnHeadMenu_OrderChanging(value);
					this.SendPropertyChanging();
					this._HeadMenu_Order = value;
					this.SendPropertyChanged("HeadMenu_Order");
					this.OnHeadMenu_OrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ShowHeadeMenu", DbType="TinyInt")]
		public System.Nullable<byte> is_ShowHeadeMenu
		{
			get
			{
				return this._is_ShowHeadeMenu;
			}
			set
			{
				if ((this._is_ShowHeadeMenu != value))
				{
					this.Onis_ShowHeadeMenuChanging(value);
					this.SendPropertyChanging();
					this._is_ShowHeadeMenu = value;
					this.SendPropertyChanged("is_ShowHeadeMenu");
					this.Onis_ShowHeadeMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> Create_at
		{
			get
			{
				return this._Create_at;
			}
			set
			{
				if ((this._Create_at != value))
				{
					this.OnCreate_atChanging(value);
					this.SendPropertyChanging();
					this._Create_at = value;
					this.SendPropertyChanged("Create_at");
					this.OnCreate_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastEdit_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastEdit_at
		{
			get
			{
				return this._LastEdit_at;
			}
			set
			{
				if ((this._LastEdit_at != value))
				{
					this.OnLastEdit_atChanging(value);
					this.SendPropertyChanging();
					this._LastEdit_at = value;
					this.SendPropertyChanged("LastEdit_at");
					this.OnLastEdit_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delete_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> Delete_at
		{
			get
			{
				return this._Delete_at;
			}
			set
			{
				if ((this._Delete_at != value))
				{
					this.OnDelete_atChanging(value);
					this.SendPropertyChanging();
					this._Delete_at = value;
					this.SendPropertyChanged("Delete_at");
					this.OnDelete_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDelete", DbType="TinyInt")]
		public System.Nullable<byte> isDelete
		{
			get
			{
				return this._isDelete;
			}
			set
			{
				if ((this._isDelete != value))
				{
					this.OnisDeleteChanging(value);
					this.SendPropertyChanging();
					this._isDelete = value;
					this.SendPropertyChanged("isDelete");
					this.OnisDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtentData", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ExtentData
		{
			get
			{
				return this._ExtentData;
			}
			set
			{
				if ((this._ExtentData != value))
				{
					this.OnExtentDataChanging(value);
					this.SendPropertyChanging();
					this._ExtentData = value;
					this.SendPropertyChanged("ExtentData");
					this.OnExtentDataChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_cmd")]
	public partial class tbl_cmd : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _name;
		
		private string _mota;
		
		private System.Nullable<System.DateTime> _create_at;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnmotaChanging(string value);
    partial void OnmotaChanged();
    partial void Oncreate_atChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_atChanged();
    #endregion
		
		public tbl_cmd()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(250)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this.OnmotaChanging(value);
					this.SendPropertyChanging();
					this._mota = value;
					this.SendPropertyChanged("mota");
					this.OnmotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_at
		{
			get
			{
				return this._create_at;
			}
			set
			{
				if ((this._create_at != value))
				{
					this.Oncreate_atChanging(value);
					this.SendPropertyChanging();
					this._create_at = value;
					this.SendPropertyChanged("create_at");
					this.Oncreate_atChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_khoahoc")]
	public partial class tbl_khoahoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _name;
		
		private string _noidung;
		
		private string _linkskhoahoc;
		
		private System.Nullable<System.DateTime> _ngaytao;
		
		private System.Nullable<byte> _ishow;
		
		private System.Nullable<byte> _isdone;
		
		private System.Nullable<byte> _isdelete;
		
		private System.Nullable<System.DateTime> _Editat;
		
		private System.Nullable<System.DateTime> _deleteat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    partial void OnlinkskhoahocChanging(string value);
    partial void OnlinkskhoahocChanged();
    partial void OnngaytaoChanging(System.Nullable<System.DateTime> value);
    partial void OnngaytaoChanged();
    partial void OnishowChanging(System.Nullable<byte> value);
    partial void OnishowChanged();
    partial void OnisdoneChanging(System.Nullable<byte> value);
    partial void OnisdoneChanged();
    partial void OnisdeleteChanging(System.Nullable<byte> value);
    partial void OnisdeleteChanged();
    partial void OnEditatChanging(System.Nullable<System.DateTime> value);
    partial void OnEditatChanged();
    partial void OndeleteatChanging(System.Nullable<System.DateTime> value);
    partial void OndeleteatChanged();
    #endregion
		
		public tbl_khoahoc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(500)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linkskhoahoc", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string linkskhoahoc
		{
			get
			{
				return this._linkskhoahoc;
			}
			set
			{
				if ((this._linkskhoahoc != value))
				{
					this.OnlinkskhoahocChanging(value);
					this.SendPropertyChanging();
					this._linkskhoahoc = value;
					this.SendPropertyChanged("linkskhoahoc");
					this.OnlinkskhoahocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaytao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaytao
		{
			get
			{
				return this._ngaytao;
			}
			set
			{
				if ((this._ngaytao != value))
				{
					this.OnngaytaoChanging(value);
					this.SendPropertyChanging();
					this._ngaytao = value;
					this.SendPropertyChanged("ngaytao");
					this.OnngaytaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ishow", DbType="TinyInt")]
		public System.Nullable<byte> ishow
		{
			get
			{
				return this._ishow;
			}
			set
			{
				if ((this._ishow != value))
				{
					this.OnishowChanging(value);
					this.SendPropertyChanging();
					this._ishow = value;
					this.SendPropertyChanged("ishow");
					this.OnishowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isdone", DbType="TinyInt")]
		public System.Nullable<byte> isdone
		{
			get
			{
				return this._isdone;
			}
			set
			{
				if ((this._isdone != value))
				{
					this.OnisdoneChanging(value);
					this.SendPropertyChanging();
					this._isdone = value;
					this.SendPropertyChanged("isdone");
					this.OnisdoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isdelete", DbType="TinyInt")]
		public System.Nullable<byte> isdelete
		{
			get
			{
				return this._isdelete;
			}
			set
			{
				if ((this._isdelete != value))
				{
					this.OnisdeleteChanging(value);
					this.SendPropertyChanging();
					this._isdelete = value;
					this.SendPropertyChanged("isdelete");
					this.OnisdeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editat", DbType="DateTime")]
		public System.Nullable<System.DateTime> Editat
		{
			get
			{
				return this._Editat;
			}
			set
			{
				if ((this._Editat != value))
				{
					this.OnEditatChanging(value);
					this.SendPropertyChanging();
					this._Editat = value;
					this.SendPropertyChanged("Editat");
					this.OnEditatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleteat", DbType="DateTime")]
		public System.Nullable<System.DateTime> deleteat
		{
			get
			{
				return this._deleteat;
			}
			set
			{
				if ((this._deleteat != value))
				{
					this.OndeleteatChanging(value);
					this.SendPropertyChanging();
					this._deleteat = value;
					this.SendPropertyChanged("deleteat");
					this.OndeleteatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_User")]
	public partial class tbl_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _tk;
		
		private string _mk;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OntkChanging(string value);
    partial void OntkChanged();
    partial void OnmkChanging(string value);
    partial void OnmkChanged();
    #endregion
		
		public tbl_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tk", DbType="NVarChar(50)")]
		public string tk
		{
			get
			{
				return this._tk;
			}
			set
			{
				if ((this._tk != value))
				{
					this.OntkChanging(value);
					this.SendPropertyChanging();
					this._tk = value;
					this.SendPropertyChanged("tk");
					this.OntkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mk", DbType="NVarChar(50)")]
		public string mk
		{
			get
			{
				return this._mk;
			}
			set
			{
				if ((this._mk != value))
				{
					this.OnmkChanging(value);
					this.SendPropertyChanging();
					this._mk = value;
					this.SendPropertyChanged("mk");
					this.OnmkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_chart")]
	public partial class tbl_chart : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private System.Nullable<int> _GiaTri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnGiaTriChanging(System.Nullable<int> value);
    partial void OnGiaTriChanged();
    #endregion
		
		public tbl_chart()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTri", DbType="Int")]
		public System.Nullable<int> GiaTri
		{
			get
			{
				return this._GiaTri;
			}
			set
			{
				if ((this._GiaTri != value))
				{
					this.OnGiaTriChanging(value);
					this.SendPropertyChanging();
					this._GiaTri = value;
					this.SendPropertyChanged("GiaTri");
					this.OnGiaTriChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_nhatki")]
	public partial class tbl_nhatki : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _name;
		
		private string _noidung;
		
		private string _mota;
		
		private System.Nullable<System.DateTime> _ngaytao;
		
		private System.Nullable<byte> _ishow;
		
		private System.Nullable<byte> _isdone;
		
		private System.Nullable<byte> _isdelete;
		
		private System.Nullable<System.DateTime> _Editat;
		
		private System.Nullable<System.DateTime> _deleteat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    partial void OnmotaChanging(string value);
    partial void OnmotaChanged();
    partial void OnngaytaoChanging(System.Nullable<System.DateTime> value);
    partial void OnngaytaoChanged();
    partial void OnishowChanging(System.Nullable<byte> value);
    partial void OnishowChanged();
    partial void OnisdoneChanging(System.Nullable<byte> value);
    partial void OnisdoneChanged();
    partial void OnisdeleteChanging(System.Nullable<byte> value);
    partial void OnisdeleteChanged();
    partial void OnEditatChanging(System.Nullable<System.DateTime> value);
    partial void OnEditatChanged();
    partial void OndeleteatChanging(System.Nullable<System.DateTime> value);
    partial void OndeleteatChanged();
    #endregion
		
		public tbl_nhatki()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(500)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(MAX)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this.OnmotaChanging(value);
					this.SendPropertyChanging();
					this._mota = value;
					this.SendPropertyChanged("mota");
					this.OnmotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaytao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaytao
		{
			get
			{
				return this._ngaytao;
			}
			set
			{
				if ((this._ngaytao != value))
				{
					this.OnngaytaoChanging(value);
					this.SendPropertyChanging();
					this._ngaytao = value;
					this.SendPropertyChanged("ngaytao");
					this.OnngaytaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ishow", DbType="TinyInt")]
		public System.Nullable<byte> ishow
		{
			get
			{
				return this._ishow;
			}
			set
			{
				if ((this._ishow != value))
				{
					this.OnishowChanging(value);
					this.SendPropertyChanging();
					this._ishow = value;
					this.SendPropertyChanged("ishow");
					this.OnishowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isdone", DbType="TinyInt")]
		public System.Nullable<byte> isdone
		{
			get
			{
				return this._isdone;
			}
			set
			{
				if ((this._isdone != value))
				{
					this.OnisdoneChanging(value);
					this.SendPropertyChanging();
					this._isdone = value;
					this.SendPropertyChanged("isdone");
					this.OnisdoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isdelete", DbType="TinyInt")]
		public System.Nullable<byte> isdelete
		{
			get
			{
				return this._isdelete;
			}
			set
			{
				if ((this._isdelete != value))
				{
					this.OnisdeleteChanging(value);
					this.SendPropertyChanging();
					this._isdelete = value;
					this.SendPropertyChanged("isdelete");
					this.OnisdeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editat", DbType="DateTime")]
		public System.Nullable<System.DateTime> Editat
		{
			get
			{
				return this._Editat;
			}
			set
			{
				if ((this._Editat != value))
				{
					this.OnEditatChanging(value);
					this.SendPropertyChanging();
					this._Editat = value;
					this.SendPropertyChanged("Editat");
					this.OnEditatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleteat", DbType="DateTime")]
		public System.Nullable<System.DateTime> deleteat
		{
			get
			{
				return this._deleteat;
			}
			set
			{
				if ((this._deleteat != value))
				{
					this.OndeleteatChanging(value);
					this.SendPropertyChanging();
					this._deleteat = value;
					this.SendPropertyChanged("deleteat");
					this.OndeleteatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
